// Code generated by gen-mapper; DO NOT EDIT.

package api

import "github.com/krendel52/gmapper/example/domain"

func MapDomainModelToApiModel(src *domain.DomainModel) *ApiModel {
	return &ApiModel{
		ID:    src.ID,
		Name:  src.Name,
		Count: src.Count,
	}
}
